# Generated by Django 2.0.1 on 2018-01-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infinitive_form',
            new_name='InfinitiveForm',
        ),
    ]
