# Generated by Django 2.0.1 on 2018-01-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0002_auto_20180126_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arabicverb',
            name='arabic_spelling',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='arabicverb',
            name='conjugated_form',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='arabicverb',
            name='en_meaning',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='arabicverb',
            name='pronunciation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='infinitiveform',
            name='arabic_spelling',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='infinitiveform',
            name='en_meaning',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='infinitiveform',
            name='infinitive_form',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='infinitiveform',
            name='pronunciation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pronoun',
            name='arabic_spelling',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pronoun',
            name='pronoun',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pronoun',
            name='pronunciation',
            field=models.CharField(max_length=30),
        ),
    ]
