# Generated by Django 2.0.1 on 2018-01-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0003_auto_20180126_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infinitiveform',
            name='infinitive_form',
        ),
    ]
