# Generated by Django 2.0.1 on 2018-01-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0004_remove_infinitiveform_infinitive_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjugatedVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_meaning', models.CharField(max_length=30)),
                ('pronunciation', models.CharField(max_length=30)),
                ('arabic_spelling', models.CharField(max_length=30)),
                ('infinitive_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabic.InfinitiveForm')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabic.Mood')),
                ('pronoun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arabic.Pronoun')),
            ],
        ),
        migrations.RemoveField(
            model_name='arabicverb',
            name='infinitive_form',
        ),
        migrations.RemoveField(
            model_name='arabicverb',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='arabicverb',
            name='pronoun',
        ),
        migrations.DeleteModel(
            name='ArabicVerb',
        ),
    ]
